spring.application.name=calidato

spring.datasource.url=jdbc:postgresql://localhost:5432/calidato
spring.datasource.username=calidato_user
spring.datasource.password=calidato_pass

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

spring.flyway.locations=classpath:db/migration